server:
  port: 9091


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Futsal
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  thymeleaf:
    cache: false
        
      
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
 